"""empty message

Revision ID: d139e5f6e2fd
Revises: aacfb422788a
Create Date: 2022-10-27 18:06:54.843218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd139e5f6e2fd'
down_revision = 'aacfb422788a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('descr', sa.VARCHAR(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'descr')
    # ### end Alembic commands ###
